default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
development:
  <<: *default
  host: localhost
  database: mmm_development
test:
  <<: *default
  host: localhost
  database: mmm_test
